"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { Card, CardContent } from "@/components/ui/Card";
import Link from "next/link";
import ReactMarkdown from "react-markdown";

export default function RequestDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const router = useRouter();
  const [request, setRequest] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [isSending, setIsSending] = useState(false);
  const [id, setId] = useState<string | null>(null);

  useEffect(() => {
    params.then(p => {
      setId(p.id);
      fetchRequest(p.id);
    });
  }, [params]);

  const fetchRequest = async (reqId: string) => {
    try {
      const res = await fetch(`/api/admin/requests/${reqId}`);
      if (res.ok) {
        const data = await res.json();
        setRequest(data);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const handleMarkAsSent = async () => {
    if (!id) return;
    setIsSending(true);
    try {
      const res = await fetch(`/api/admin/requests/${id}/send`, {
        method: "POST"
      });
      if (res.ok) {
        alert("Marked as SENT! (Email sending is currently skipped per your request)");
        router.push("/admin/requests");
      } else {
        alert("Failed to mark as sent.");
      }
    } catch (e) {
      alert("Error.");
    } finally {
      setIsSending(false);
    }
  };

  if (loading) return <div className="p-8 text-center text-gray-500">Loading request...</div>;
  if (!request) return <div className="p-8 text-center text-red-500">Request not found.</div>;

  let answers = {};
  try { answers = JSON.parse(request.answers); } catch (e) {}

  return (
    <div>
      <div className="mb-6 flex justify-between items-center">
        <div className="flex items-center gap-4">
          <Link href="/admin/requests" className="text-gray-500 hover:text-gray-900">
            ← Back
          </Link>
          <h1 className="text-2xl font-bold text-gray-900">Review Request</h1>
          <Badge variant={request.status === "SENT" ? "success" : "warning"}>{request.status}</Badge>
        </div>
        
        {request.status === "PENDING" && (
          <Button onClick={handleMarkAsSent} isLoading={isSending}>
            Mark as Sent (Skip Email)
          </Button>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Sidebar: User Details */}
        <div className="col-span-1 space-y-6">
          <Card>
            <div className="px-5 py-4 border-b border-gray-200">
              <h3 className="text-lg font-medium">User Profile</h3>
            </div>
            <CardContent className="space-y-4 pt-4">
              <div>
                <label className="block text-xs font-medium text-gray-500 uppercase">Name</label>
                <div className="text-sm font-medium">{request.user.name || "Unknown"}</div>
              </div>
              <div>
                <label className="block text-xs font-medium text-gray-500 uppercase">Email</label>
                <div className="text-sm font-medium">{request.user.email}</div>
              </div>
              <div>
                <label className="block text-xs font-medium text-gray-500 uppercase">Requested Content</label>
                <div className="text-sm font-medium text-[#10b981]">{request.content.title}</div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <div className="px-5 py-4 border-b border-gray-200">
              <h3 className="text-lg font-medium">Survey Answers</h3>
            </div>
            <CardContent className="space-y-4 pt-4">
              {Object.entries(answers).map(([key, value]) => (
                <div key={key} className="pb-3 border-b border-gray-100 last:border-0 last:pb-0">
                  <div className="text-xs font-medium text-gray-500 uppercase mb-1">{key}</div>
                  <div className="text-sm font-medium">{value as string}</div>
                </div>
              ))}
            </CardContent>
          </Card>
        </div>

        {/* Main: AI Generated Content */}
        <div className="col-span-2">
          <Card className="h-full">
            <div className="px-5 py-4 border-b border-gray-200 flex justify-between items-center">
              <h3 className="text-lg font-medium">AI Generated Plan</h3>
              <div className="text-xs text-gray-500">Generated by GPT-4o-mini</div>
            </div>
            <CardContent className="pt-6">
              <div className="prose prose-base md:prose-lg max-w-none prose-stone dark:prose-invert bg-white dark:bg-stone-900 p-8 md:p-12 rounded-2xl border border-stone-200 dark:border-stone-800 shadow-sm overflow-y-auto max-h-[800px] leading-relaxed">
                {request.generatedContent ? (
                  <ReactMarkdown>{request.generatedContent}</ReactMarkdown>
                ) : (
                  <div className="text-stone-500 italic">No content generated.</div>
                )}
              </div>
            </CardContent>
          </Card>
        </div>

      </div>
    </div>
  );
}
