import "dotenv/config";
import { generateImage } from "../lib/ai";
import fs from "fs";
import path from "path";
import sharp from "sharp";

async function testImageGen() {
  console.log("🎨 Testing AI Image Generation...");
  
  const prompt = "A cinematic, professional food photography shot of a vibrant Mediterranean salad with olives and feta, soft lighting, high resolution";
  
  try {
    const rawData = await generateImage(prompt);
    console.log("✅ Image generated by AI.");

    const uploadDir = path.join(process.cwd(), "public", "test");
    if (!fs.existsSync(uploadDir)) {
      fs.mkdirSync(uploadDir, { recursive: true });
    }

    const fileName = `test-ai-image-${Date.now()}.jpg`;
    const filePath = path.join(uploadDir, fileName);

    if (rawData.startsWith("data:")) {
      const base64Data = rawData.split(",")[1];
      const buffer = Buffer.from(base64Data, "base64");
      
      await sharp(buffer)
        .resize(1200)
        .jpeg({ quality: 85 })
        .toFile(filePath);
    } else {
      // It's a URL
      const response = await fetch(rawData);
      const buffer = Buffer.from(await response.arrayBuffer());
      
      await sharp(buffer)
        .resize(1200)
        .jpeg({ quality: 85 })
        .toFile(filePath);
    }

    console.log(`✅ Image saved successfully to: ${filePath}`);
    console.log(`🔗 Try to browse it at: /test/${fileName}`);
  } catch (error) {
    console.error("❌ Test failed:", error);
  }
}

testImageGen();
